input_dir: /storage/home/hcoda1/2/hwilms3/scratch/MW153/outputs_MW153_array
output_dir: /storage/home/hcoda1/2/hwilms3/scratch/MW153/outputs_MW153_array/other_bugs_PAO1_report

file_patterns:
  decoy_sam: "*.mapped_to_other_bugs.sam"

pao1:
  reference_dir: /storage/home/hcoda1/2/hwilms3/r-mwhiteley3-0/referencegenomes
  fasta_extensions: ["Pseudomonas_aeruginosa_PAO1_107.fna", "*.fa", "*.fasta", "*.fna"]
  gff_extensions: ["Pseudomonas_aeruginosa_PAO1_107.gff3", "*.gff", "*.gff3"]

settings:
  threads: 16
  top_n: 30
  featurecounts_stranded: 1
  featurecounts_feature_type: CDS
  featurecounts_gene_attribute: locus
  skip_secondary_alignments: true
  overwrite_existing: false