input:
  #fastq_glob: "/storage/home/hcoda1/2/hwilms3/scratch/MW153/outputs_MW153_array/other_bugs_PAO1_report/*/*.decoy_filtered.PAO1_unmapped.fastq.gz"
  fastq_glob: "/storage/home/hcoda1/2/hwilms3/scratch/MW153/outputs_MW153_array/other_bugs_PAO1_report/*AB33*/*.decoy_filtered.PAO1_unmapped.fastq.gz"
  sample_ref_match_csv: "sample_ref_match.csv"

output_dir: "/storage/home/hcoda1/2/hwilms3/scratch/MW153/outputs_MW153_array/non_PAO1_gene_mapping_report"

references:
  - name: mouse_GRCm39
    reference_dir: "/storage/home/hcoda1/2/hwilms3/r-mwhiteley3-0/refs"
    fasta: "mouse_GCF_000001635.27_GRCm39_genomic.fna"
    gff: "mouse_GCF_000001635.27_GRCm39_genomic.gff"
    index_prefix: "mouse_GCF_000001635.27_GRCm39_genomic"
    feature_type: "gene"
    gene_attribute: "Name"

  - name: human_GRCh38
    reference_dir: "/storage/home/hcoda1/2/hwilms3/r-mwhiteley3-0/refs"
    fasta: "human_GRCh38.fna"
    gff: "human_GRCh38.gff"
    index_prefix: "human_GRCh38"
    feature_type: "gene"
    gene_attribute: "Name"

  - name: rat_GRCr8
    reference_dir: "/storage/home/hcoda1/2/hwilms3/r-mwhiteley3-0/refs"
    fasta: "rat_GCF_036323735.1_GRCr8_genomic.fna"
    gff: "rat_GCF_036323735.1_GRCr8_genomic.gff"
    index_prefix: "rat_GCF_036323735.1_GRCr8_genomic"
    feature_type: "gene"
    gene_attribute: "Name"

bowtie2:
  threads: 16
  mode: "--end-to-end"
  extra_args:
    - "--very-sensitive"

featurecounts:
  threads: 16
  stranded: 0
  allow_multi_overlap: false

settings:
  overwrite_existing: false
  keep_sam: true
  continue_on_error: false
